[package]
name = "nginpay"
version = "0.1.0"
edition = "2021"
rust-version = "1.58"

[dependencies]
anyhow = "1.0"
csv = "1.1"
env_logger = "0.9"
log = "0.4"
serde = { version = "1.0", features = [ "derive" ] }
structopt = "0.3"
